//
//  exception_capture.c
//  lucerne
//
//  Created by Antoine on 28/05/2025.
//  

#include "exception_capture.h"
#include <dispatch/dispatch.h>
#include <mach/exc.h>
#include <Kernel/mach/exc_server.h>
#include <sys/ptrace.h>
#include <errno.h>
#include <string.h>
#include <mach/thread_act.h>
#include <Kernel/mach/exception_types.h>

#include "autogenerated/mach_exc_server.h"
#include "autogenerated/mach_exc.h"
#include "exception_capture.h"
#include <stdio.h>

typedef struct {
    mach_msg_header_t head;
    uint8_t data[8192];
} MachMessageBuffer;

static dispatch_queue_t exception_handling_queue;

boolean_t mach_exc_server
(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

void handle_exceptions(mach_port_t exception_port) {
    
    while (true) {
        
        MachMessageBuffer *request_buffer = malloc(sizeof(MachMessageBuffer));
        MachMessageBuffer *reply_buffer = malloc(sizeof(MachMessageBuffer));
        
        mach_msg_return_t result = mach_msg(&request_buffer->head,
                                            MACH_RCV_MSG | MACH_RCV_TIMEOUT,
                                            0,
                                            sizeof(MachMessageBuffer),
                                            exception_port,
                                            10000,
                                            MACH_PORT_NULL);
        
        if (result == MACH_RCV_TIMED_OUT) {
            continue;
        }
        
        if (result != MACH_MSG_SUCCESS) {
            printf("mach_msg receive failed: %s\n", mach_error_string(result));
            continue;
        }
        
        // Handle the exception
        if (!mach_exc_server(&request_buffer->head, &reply_buffer->head)) {
            printf("mach_exc_server could not handle message\n");
            continue;
        }
        
        // Send reply back to the task
        kern_return_t kr = mach_msg(&reply_buffer->head,
                                  MACH_SEND_MSG,
                                  reply_buffer->head.msgh_size,
                                  0,
                                  MACH_PORT_NULL,
                                  MACH_MSG_TIMEOUT_NONE,
                                  MACH_PORT_NULL);
        
        if (kr != KERN_SUCCESS) {
            printf("Failed to send reply: %s\n", mach_error_string(kr));
        } else {
            printf("sent reply successfully\n");
        }
        
//        free(request_buffer);
//        free(reply_buffer);
    }
}


void catch_exceptions_for(lucerne_target *target) {
    mach_port_t exception_port;
    kern_return_t kr;
    
    printf("Setting up exception port for target pid %d\n", pid_for_target(target));
    
    // Allocate and set up our exception port
    kr = mach_port_allocate(mach_task_self(), MACH_PORT_RIGHT_RECEIVE, &exception_port);
    if (kr != KERN_SUCCESS) {
        printf("mach_port_allocate failed: %s\n", mach_error_string(kr));
        return;
    }
    printf("Exception port allocated successfully\n");
    
    kr = mach_port_insert_right(mach_task_self(),
                                exception_port, exception_port, MACH_MSG_TYPE_MAKE_SEND);
    if (kr != KERN_SUCCESS) {
        printf("mach_port_insert_right failed: %s\n", mach_error_string(kr));
        return;
    }
    printf("Exception port rights inserted\n");
    
    // Set up our exception handler
    printf("Setting exception ports for task...\n");
    kr = task_set_exception_ports(target->task,
                                  EXC_MASK_ALL,
                                 exception_port,
                                 EXCEPTION_DEFAULT | MACH_EXCEPTION_CODES,
                                 ARM_THREAD_STATE64);
    if (kr != KERN_SUCCESS) {
        printf("task_set_exception_ports failed: %s\n", mach_error_string(kr));
        return;
    }
    printf("Exception ports set successfully\n");
    
    // Create a dispatch queue for exception handling if it doesn't exist
    if (!exception_handling_queue) {
        exception_handling_queue = dispatch_queue_create("com.antoine.lucerne.exception_handler", NULL);
    }
    
    // Start exception handling on the dispatch queue
    printf("Starting exception handler loop...\n");
    dispatch_async(exception_handling_queue, ^{
        handle_exceptions(exception_port);
    });
}

kern_return_t catch_mach_exception_raise
(
    mach_port_t exception_port,
    mach_port_t thread,
    mach_port_t task,
    exception_type_t exception,
    mach_exception_data_t code,
    mach_msg_type_number_t codeCnt
 ) {
    pid_t target_pid;
    pid_for_task(task, &target_pid);
    printf("Caught exception type: %d for pid %d (thread: %d)\n", exception, target_pid, thread);
    int should_resume = 0;

    // Print exception details
    switch (exception) {
        case EXC_BAD_ACCESS:
            printf("Bad memory access at address: %llx\n", code[0]);
            break;
        case EXC_BAD_INSTRUCTION:
            printf("Bad instruction at address: %llx\n", code[0]);
            break;
        case EXC_ARITHMETIC:
            printf("Arithmetic exception\n");
            break;
        case EXC_SOFTWARE: {
            printf("Software exception with code[0]=%llx, code[1]=%llx, code[2]=%llx\n", 
                   code[0], code[1], code[2]);
            
            // selected_thread_id == -1 means that we still haven't determined a thread to select as default
            // we don't really have an algorithim for determining
            if (get_connected_target() && get_connected_target()->selected_thread_id == -1) {
                thread_suspend(thread);
                
                thread_identifier_info_data_t id_info_data;
                mach_msg_type_number_t count = THREAD_IDENTIFIER_INFO_COUNT;
                
                kern_return_t kr = thread_info(thread, THREAD_IDENTIFIER_INFO, (thread_info_t)&id_info_data, &count);
                if (kr != KERN_SUCCESS) {
                    printf("Couldn't get thread id of thread %d?!\n", thread);
                } else {
                    get_connected_target()->selected_thread_id = id_info_data.thread_id;
                    printf("selected thread id: %lld\n", id_info_data.thread_id);
                }
            }
//            if (code[0] == EXC_SOFT_SIGNAL) {
//                printf("Handling soft signal (SIGSTOP=%d)\n", code[2] == SIGSTOP);
//                if (code[2] == SIGSTOP) {
//                    // If SIGSTOP, do not resume the thread
//                    should_resume = 0;
//                } else {
//                    // For other soft signals, resume
//                    should_resume = 1;
//                }
//                int ptrace_ret = ptrace(PT_THUPDATE,
//                                        target_pid,
//                                        (caddr_t)(uintptr_t)thread,
//                                        code[1]);
//                printf("PT_THUPDATE ret: %d\n", ptrace_ret);
//            }
            break;
        }
        default:
            printf("Unknown exception type\n");
            break;
    }

    if (should_resume) {
        kern_return_t kr = thread_resume(thread);
        if (kr != KERN_SUCCESS) {
            printf("Failed to resume thread: %s\n", mach_error_string(kr));
        } else {
            printf("Thread resumed after exception\n");
        }
    } else {
        printf("Thread left suspended due to SIGSTOP\n");
    }

    return KERN_SUCCESS;
}

// This isn't really used, but
// we need to have it anyway since Apple's mig code requires it
kern_return_t catch_mach_exception_raise_state
(
    mach_port_t exception_port,
    exception_type_t exception,
    const mach_exception_data_t code,
    mach_msg_type_number_t codeCnt,
    int *flavor,
    const thread_state_t old_state,
    mach_msg_type_number_t old_stateCnt,
    thread_state_t new_state,
    mach_msg_type_number_t *new_stateCnt
 ) {
    printf("%s\n", __func__);
    return MACH_RCV_INVALID_TYPE;
}

// Same comments on catch_mach_exception_raise_state apply
kern_return_t catch_mach_exception_raise_state_identity
(
    mach_port_t exception_port,
    mach_port_t thread,
    mach_port_t task,
    exception_type_t exception,
    mach_exception_data_t code,
    mach_msg_type_number_t codeCnt,
    int *flavor,
    thread_state_t old_state,
    mach_msg_type_number_t old_stateCnt,
    thread_state_t new_state,
    mach_msg_type_number_t *new_stateCnt
 ) {
    printf("%s\n", __func__);
    return MACH_RCV_INVALID_TYPE;
}

