//
//  target.c
//  lucerne
//
//  Created by Antoine on 26/05/2025.
//  

#include "target.h"
#include <mach/mach.h>
#include <sys/_types/_pid_t.h>
#include <libproc.h>
#include <stdlib.h>
#include <stdio.h>
#include <dispatch/dispatch.h>
#include <mach/exc.h>
#include <Kernel/mach/exc_server.h>
#include <sys/ptrace.h>
#include <errno.h>
#include <mach/task.h>
#include <sys/wait.h>

#include "autogenerated/mach_exc_server.h"
#include "autogenerated/mach_exc.h"
#include "exception_capture.h"

static lucerne_target *connected_target = NULL;
// TODO: - Cleanup
static dispatch_queue_t target_death_observer_dispatch_queue;
static struct kevent target_death_kevent_observer;
static int target_death_kqueue;

pid_t pid_for_target(lucerne_target *target) {
    pid_t p;
    pid_for_task(target->task, &p);
    return p;
}

lucerne_target *get_connected_target(void) {
    return connected_target;
}

int ptrace_attach_exc_robust(pid_t p);

bool set_connected_target(lucerne_target *target) {
//    printf("Setting up target with pid %d\n", pid_for_target(target));
    connected_target = target;
    
    if (!target_death_observer_dispatch_queue)
        target_death_observer_dispatch_queue = dispatch_queue_create("com.antoine.lucerne.target_death_observer", NULL);
    
//    kern_return_t get_kr = task_get_exception_ports(target->task,
//                                                    EXC_MASK_BAD_ACCESS,
//                             target->saved_masks,
//                             &target->saved_exception_types_count,
//                             target->saved_ports,
//                             target->saved_behaviors,
//                             target->saved_flavors);
//    printf("get_kr: %s\n", mach_error_string(get_kr));
    
//    printf("Setting up exception handling...\n");
    catch_exceptions_for(target);
//    printf("Exception handling setup complete\n");
    
//    printf("Attempting ptrace(PT_ATTACHEXC)...\n");
    int ptrace_ret = ptrace(PT_ATTACHEXC, pid_for_target(target), 0, 0);
    if (ptrace_ret == -1) {
        printf("ptrace_ret error: %s\n", mach_error_string(errno));
        return false;
    }
//    printf("PT_ATTACHEXC was a success\n");
    
    dispatch_async(target_death_observer_dispatch_queue, ^{
        
        target_death_kqueue = kqueue();
        
        EV_SET(&target_death_kevent_observer,
               pid_for_target(target),
               EVFILT_PROC,
               EV_ADD, NOTE_EXIT | NOTE_EXITSTATUS | NOTE_EXIT_DETAIL, 0, NULL);
        
        // this is blocking (which is why we run it on an async q)
        int result = kevent(target_death_kqueue, &target_death_kevent_observer, 1, NULL, 0, NULL);
        
        if (result == -1) {
            perror("kevent :(");
        } else if (result > 0) {
            if (target_death_kevent_observer.fflags & NOTE_EXIT) {
                printf("\nProcess %d has exited. Disconnecting.\n", pid_for_target(target));
                disconnect_target();
            }
        }
    });
    
    return true;
}

void disconnect_target(void) {
    
    if (get_connected_target()) {
        // First detach from the process using ptrace
        pid_t target_pid = pid_for_target(get_connected_target());
        int detach_ret = ptrace(PT_DETACH, target_pid, 0, 0);
        if (detach_ret == -1) {
            printf("Warning: Failed to detach from process: %s\n", strerror(errno));
        } else {
            printf("Successfully detached from process\n");
        }

        // Clean up kqueue monitoring
        EV_SET(&target_death_kevent_observer, target_pid, EVFILT_PROC, EV_DELETE, 0, 0, NULL);
        kevent(target_death_kqueue, &target_death_kevent_observer, 1, NULL, 0, NULL);
        
        close(target_death_kqueue);
        
        free(connected_target);
        connected_target = NULL;
    }
}

lucerne_init_target_result
lc_init_target_from_pid(pid_t pid, lucerne_target **target) {
    // first, let's get task_for_pid, this is mainly what we care about
    // (the name property is more so just for show if needed)
    task_t tsk;
    kern_return_t kr = task_for_pid(mach_task_self(), pid, &tsk); /* the secret ingredient */
    
    if (kr != KERN_SUCCESS) {
        // failed :(
        target = NULL;
        return (lucerne_init_target_result){
            .code = lucerne_init_target_kr_err,
            .kr_error = kr
        };
    }
    
    // alocate and prepare some more stuff: name, threads
    char *name = malloc(2*MAXCOMLEN);
    proc_name(pid, name, 2*MAXCOMLEN);
    
    // Suspend before we analyze threads
//    task_suspend(tsk);
    
    *target = malloc(sizeof(lucerne_target));
    (*target)->task = tsk;
    (*target)->selected_thread_id = -1; // still haven't selected a thread
    
//    (*target)->threads = target_threads;
//    (*target)->threads_count = threads_count;
    
    return (lucerne_init_target_result) {
        .code = lucerne_init_target_success,
        .kr_error = -1
    };
};

lucerne_init_target_result
lc_init_target_from_name(const char *user_input_name, lucerne_target **target) {
    
    // get all pid names, iterate, and find the ones that match the name
    // TODO: - Change pids to be allocated depending on how many pids actually exist with malloc
    // (and not just hardcoding 1024)
    pid_t pids[1024];
    int count = proc_listpids(PROC_ALL_PIDS, 0, pids, sizeof(pids));
    
    // There may be multiple processes with the same name,
    // so lets a store an array of indices (of the pid array)
    // to later give the user choice of which they want to select
    int indices[200] = {0};
    unsigned int indicesSize = 0; // amount of indices actually in the array
    
    for (int i = 0; i < count; i++) {
        char process_name[2*MAXCOMLEN];
        proc_name(pids[i], process_name, sizeof(process_name));
        
        if (strcmp(user_input_name, process_name) == 0) {
            // insert index
            indices[indicesSize] = i;
            indicesSize++;
        }
    }
    
    switch (indicesSize) {
        case 0: // no procs match the name :(
            return (lucerne_init_target_result) {
                .code = lucerne_init_target_not_found,
                .kr_error = -1
            };
        case 1: { // ideal (and most common) case: exactly one proc matches that name, we can connect right away
            int index = indices[0];
            return lc_init_target_from_pid(pids[index], target);
        }
        default: { // >1, give the user a choice
            // TODO: - Remove user choice, just show possible PIDs and tell the user to specify which one in another connect command
            pid_t *user_choices = malloc(indicesSize*sizeof(pid_t));
            for (int i = 0; i < indicesSize; i++) {
                user_choices[i] = pids[indices[i]]; // wow this SUCKS LOL
            }
            
            return (lucerne_init_target_result) {
                .code = lucerne_init_target_multiple_found,
                .kr_error = -1,
                .choices = user_choices,
                .choices_count = indicesSize
            };
        }
    }
}

//mach_port_t create_exception_port(void) {
//    mach_port_t exception_port;
//    mach_port_allocate(mach_task_self(), MACH_PORT_RIGHT_RECEIVE, &exception_port);
//    kern_return_t kr = mach_port_insert_right(mach_task_self(), exception_port, exception_port, MACH_MSG_TYPE_MAKE_SEND);
//    printf("mach_port_insert_right: %s\n", mach_error_string(kr));
//    return exception_port;
//}
